import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.Reader;
import java.util.Arrays;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {

    // Path or File if Path doesn't work

    // Create a new file

    // Pass it into a reader


    BufferedReader successfulRead = FileReadAndWrite.fileToReaderObject();


    // Reader passes all of that to gSON


    // gSon parses from JSON to Java objects
        // --> creates a list of Java Book Objects


    // now we have objects get random quote and author

        // --> print those data


    ///////////////////////////// -- Test bed

        Gson gson = new Gson();
        Book[] books = gson.fromJson(successfulRead, Book[].class);

        System.out.println(books[9].toString());


    }
}
