/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.google.gson.Gson;
import org.junit.Test;

import java.io.BufferedReader;

import static org.junit.Assert.*;

public class AppTest {

    /*
    * Tests:--> Check that toString == books[0] (write expected return format)*/


    @Test public void testBookToString() {
        BufferedReader successfulRead = FileReadAndWrite.fileToReaderObject();

        // use Gson to read the data and turn it into a book class
        Gson gson = new Gson();
        Book[] books = gson.fromJson(successfulRead, Book[].class);
        String expectedTest = "Quote: “I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love.” - Author: Marilyn Monroe";
        System.out.println(books[0].toString());
        assertEquals("Our expected text should equal the book.toString method", expectedTest, books[0].toString());

//        App classUnderTest = new App();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }


}
